<?php
/**
* Template Name: Gallery
* @package	Inbound Email
* 
*/

$key = basename(dirname(__FILE__));


/* Configures Template Information */
$inbound_email_data[$key]['info'] = array(
	'data_type' =>'email-template',
	'label' => __( 'Gallery' , 'inbound-mailer') ,
	'category' => 'responsive',
	'demo' => '',
	'description' => __( 'Gallery email template' , 'inbound-mailer' ),
	'acf' => true
);

/*
* Define ACF Fields to be used in this template
* Pay special attention to the 'location' key as this is where we tell ACF to load when this template is selected
*/
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55e45e5ee1057',
	'title' => 'Gallery',
	'fields' => array (
		array (
			'key' => 'field_55e45e6d5e11b',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55e45e848413f',
			'label' => 'Logo Image',
			'name' => 'logo_url',
			'type' => 'image',
			'instructions' => 'Please add your logo. It will be positioned at the center of the header. The logo max height is 100 pixels. A bigger logo will be resized.
Please notice that png files are not read correctly by Outlook, if you want maximum cross client compatibility use jpg images.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55e4600d12a1f',
			'label' => 'Header Background Color',
			'name' => 'header_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#dfdfdf',
		),
		array (
			'key' => 'field_55e460be3b234',
			'label' => 'Home Page URL',
			'name' => 'home_page_url',
			'type' => 'url',
			'instructions' => 'Add the URL of the page you want to send people to when they click on the logo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55e4634d3036e',
			'label' => 'Email Body',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55e4637a0f031',
			'label' => 'Email Title',
			'name' => 'email_title',
			'type' => 'text',
			'instructions' => 'Latest products from our shop',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55e46d00643b6',
			'label' => 'Email Background Color',
			'name' => 'email_bg_color',
			'type' => 'color_picker',
			'instructions' => 'You can set a background color for your email. The default is a light grey that helps highlighting the gallery images',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#dfdfdf',
		),
		array (
			'key' => 'field_55e46500ff1e2',
			'label' => 'Gallery',
			'name' => 'gallery',
			'type' => 'flexible_content',
			'instructions' => 'Here you add your gallery of images with links and descriptions',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Row',
			'min' => 1,
			'max' => '',
			'layouts' => array (
				array (
					'key' => '55e465131439e',
					'name' => 'gallery_row',
					'label' => 'Gallery Row',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55e466d8ff1e3',
							'label' => 'Left Image',
							'name' => 'left_image',
							'type' => 'image',
							'instructions' => 'Image on the left side of the row. Image must be 270 pixels wide X 200 pixels high. Images of different sizes will be resized.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_55e46c0344bea',
							'label' => 'Left Image URL',
							'name' => 'left_image_url',
							'type' => 'url',
							'instructions' => 'Add the URL of the landing page/product page to send users that clik on the image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#',
							'placeholder' => '',
						),
						array (
							'key' => 'field_55e46b5a44be8',
							'label' => 'Left Image Title',
							'name' => 'left_image_title',
							'type' => 'text',
							'instructions' => 'Add the title of your image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Lorem ipsum dolor sit amet',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55e46bb044be9',
							'label' => 'Left Image Title URL',
							'name' => 'left_image_title_url',
							'type' => 'url',
							'instructions' => 'You can send the user that clicks to the title to a special URL, or use the same that you use for the image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#',
							'placeholder' => '',
						),
						array (
							'key' => 'field_55e46cb12f266',
							'label' => 'Left Image Author or Description',
							'name' => 'left_image_author',
							'type' => 'text',
							'instructions' => 'Add the author or descriptoin of the image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Hari Seldon',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55e4707148f1a',
							'label' => 'Right Image',
							'name' => 'right_image',
							'type' => 'image',
							'instructions' => 'Image on the right side of the row. Image must be 270 pixels wide X 200 pixels high. Images of different sizes will be resized. You can leave it empty if you don\'t have any more images to add',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_55e470ff60945',
							'label' => 'Right Image URL',
							'name' => 'right_image_url',
							'type' => 'url',
							'instructions' => 'Add the URL of the landing page/product page to send users that clik on the image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#',
							'placeholder' => '',
						),
						array (
							'key' => 'field_55e4711a60946',
							'label' => 'Right Image Title',
							'name' => 'right_image_title_copy',
							'type' => 'text',
							'instructions' => 'Add the title of your image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Lorem ipsum dolor sit amet',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55e4714360947',
							'label' => 'Right Image Title URL',
							'name' => 'right_image_title_url',
							'type' => 'url',
							'instructions' => 'You can send the user that clicks to the title to a special URL, or use the same that you use for the image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#',
							'placeholder' => '',
						),
						array (
							'key' => 'field_55e4715e60948',
							'label' => 'Right Image Author or Description',
							'name' => 'right_image_author',
							'type' => 'text',
							'instructions' => 'Add the author or descriptoin of the image',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Hari Seldon',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'inbound-email',
			),
			array (
				'param' => 'template_id',
				'operator' => '==',
				'value' => $key,
			)
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;